language: python
python:
    - "3.3"
virtualenv:
    system_site_packages: true
before_install:
    - sudo apt-get build-dep -qq python-numpy python-scipy
install:
    - "pip install networkx"
    - "pip install numpy"
    - "pip install scipy"
script: nosetests
notifications:
    email: false
